
override INT_CFLAGS += -fno-pie -ffreestanding -nostdinc -nostdlib -nostartfiles -fno-exceptions -mno-outline-atomics -march=armv8-a+nofp
override INT_CXXFLAGS += -fno-pie -ffreestanding -nostdinc -nostdlib -nostartfiles -fno-exceptions -mno-outline-atomics -march=armv8-a+nofp
override INT_LDFLAGS  += -nostdlib

override INT_CFLAGS += -fno-stack-protector
override INT_CXXFLAGS += -fno-stack-protector
